### ISSUE TITLE
AWS::ECR::Repository-EncryptionConfiguration

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/aws-cloudformation-resource-providers-ecr#15]
Cross posting here for tracking.

https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/654

```
As of Jul 29, 2020 ECR now supports encryption of images using AWS KMS keys.
https://aws.amazon.com/about-aws/whats-new/2020/07/ecr-supports-encryption-images-aws-kms-keys/

Please add EncryptionConfiguration property to AWS::ECR::Repository resource type.

AWS::ECR::Repository
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html

EncryptionConfiguration
https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_EncryptionConfiguration.html
```

**Comment by apurvmahajan** [comment]
Thank you for opening this issue. We have now have this issue under consideration.

**Comment by pplu** [comment]
JFYI: This is a feature that is being asked for here too: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/771

**Comment by neijurli** [comment]
The property is now supported: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-encryptionconfiguration. 

You can also find the specific details to the new property in the resource specifications [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html).
